### ISSUE TITLE
remove deletes within your tests 

### ISSUE THREAD

**Issue by ateevnahar** [danielgaooooo/a1p2#13]
those are local variables within a function doing a delete as you do leads to memory issues. I can open a pr to fix you tests.

**Comment by danielgaooooo** [comment]
can you link me to each of the instances where I am leaking memory? I am happy to fix it

**Comment by ateevnahar** [comment]
in your string test for example all the deletes are unneeded (also if you are in wvh we can talk in person) Sorry for the crop of issues

**Comment by danielgaooooo** [comment]
How come all of the `deletes` are unneeded? I believe since they all my variables in `testString` are allocated via the `new` keyword, the `delete` is required to free them from heap space, or else the operating system is forced to clean up after the program exits. As in, the `delete` statements are necessary to prevent memory leaks. They don't cause them.

**Comment by ateevnahar** [comment]
should I send you my string class?
It is a local variable so it cleans after itself. I am gonna include and error I got when I kept your deletes in
`map-tests(20592,0x112c87dc0) malloc: *** error for object 0x10e514e55: pointer being freed was not allocated
map-tests(20592,0x112c87dc0) malloc: *** set a breakpoint in malloc_error_break to debug`

**Comment by danielgaooooo** [comment]
whenever you allocate anything with `new`, you must call `delete` - this is a C++ standard.  
```
String* str = new String();
... do some stuff ...
delete str;
```
no matter what, once you are done with `str`, you need to delete it. that error looks like an issue with how your string destructor cleans up its memory, not our tests.  
check out this q&a for [reference](https://stackoverflow.com/questions/13148119/what-does-pointer-being-freed-was-not-allocated-mean-exactly)

**Comment by ateevnahar** [comment]
When they removed your test passed. also you don't even need to test string. actually I bet this due to concat since you are supposed return a new object but your behavior via tests mean to mutate.

**Comment by ateevnahar** [comment]
tbh doesn't matter gonna ignore these tests cause we did not have to do them.

**Comment by danielgaooooo** [comment]
Our test behavior actually does not mutate, it creates a new `String` object every time. Otherwise, this test would not work `t_true(bob->concat(ann)->equals(bobAnnCopy))`. I will remove `testString` because it is not necessary for this assignment, but I'll warn you that there is definitely something wrong with your destructor

**Comment by ateevnahar** [comment]
hey I suck at c and found the issue, it was with the empty constructor you asked us to implement. My partner did it wrong which lead to this.
btw here is our deconstructor  which I am very sure is correct.  
![image](https://user-images.githubusercontent.com/8186385/73573610-c3fe3000-4441-11ea-9f99-da366a4a5bee.png)

**Comment by ateevnahar** [comment]
thanks for being so responsive.
