### ISSUE TITLE
Errors in the test-map.cpp

### ISSUE THREAD

**Issue by obrahme** [danielgaooooo/a1p2#2]
When you create a String object it requires a string value, it can't be left empty.
ex: String* empty = new String();  <---("")
This does not follow the constructor specification you gave for the string class.
Please fix this on all the instances in the map-test.cpp file.

**Comment by danielgaooooo** [comment]
Hey - I added a default constructor `String()` to the `string.h`. If this fixes your issue, please go ahead and close. Otherwise, let me know what else I need to do. I believe this issue arose once we migrated from our original `string.h` file to the "common" header provided by a student on Piazza. Feel free to add your own implementation of `String()`
